/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cafe.quanlisp;

import cafe.quanlikh.ConnectDB;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class themsanpham extends javax.swing.JDialog {

    /**
     * Creates new form themsanpham
     */
    public themsanpham(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    private sanpham parentForm;

    private File selectedFile;

    public themsanpham(sanpham parentForm) {
        this.parentForm = parentForm; // Lưu tham chiếu vào biến
        initComponents();
        this.setLocationRelativeTo(null);
        loadCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        masp = new javax.swing.JLabel();
        tensp1 = new javax.swing.JLabel();
        giabansanpham1 = new javax.swing.JLabel();
        motasp1 = new javax.swing.JLabel();
        trangthaisp = new javax.swing.JLabel();
        tennhacungcap1 = new javax.swing.JLabel();
        hinhanh = new javax.swing.JLabel();
        tenncctxt = new javax.swing.JTextField();
        motatxt = new javax.swing.JTextField();
        anhtxt = new javax.swing.JTextField();
        giasptxt = new javax.swing.JTextField();
        tensptxt = new javax.swing.JTextField();
        buttonluu = new javax.swing.JButton();
        maloai = new javax.swing.JLabel();
        masptxt = new javax.swing.JTextField();
        buttonluu1 = new javax.swing.JButton();
        maloaicombobox = new javax.swing.JComboBox<>();
        chonanhbutton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        anhlabble = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(177, 151, 125));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thêm sản phẩm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nhập thông tin sản phẩm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        masp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        masp.setText("Mã sản phẩm");

        tensp1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tensp1.setText("Tên sản phẩm");

        giabansanpham1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        giabansanpham1.setText("Giá bán sản phẩm");

        motasp1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        motasp1.setText("Mô tả sản phẩm");

        trangthaisp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        trangthaisp.setText("Trạng thái sản phẩm");

        tennhacungcap1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tennhacungcap1.setText("Tên nhà cung cấp");

        hinhanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hinhanh.setText("Hình ảnh sản phẩm");

        motatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motatxtActionPerformed(evt);
            }
        });

        buttonluu.setBackground(new java.awt.Color(177, 151, 125));
        buttonluu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonluu.setForeground(new java.awt.Color(255, 255, 255));
        buttonluu.setText("Thêm");
        buttonluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonluuActionPerformed(evt);
            }
        });

        maloai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maloai.setText("Mã loại");

        masptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masptxtActionPerformed(evt);
            }
        });

        buttonluu1.setBackground(new java.awt.Color(177, 151, 125));
        buttonluu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonluu1.setForeground(new java.awt.Color(255, 255, 255));
        buttonluu1.setText("Hủy");
        buttonluu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonluu1ActionPerformed(evt);
            }
        });

        chonanhbutton.setText("Chọn ảnh");
        chonanhbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonanhbuttonActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn hàng", "Hết hàng", "Ngừng bán" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tensp1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giabansanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motasp1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tennhacungcap1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trangthaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chonanhbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(giasptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenncctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(masptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maloai, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(maloaicombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tensptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(anhlabble, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonluu)
                            .addComponent(buttonluu1))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(masp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maloai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(masptxt, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(maloaicombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tensp1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tensptxt, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giabansanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giasptxt, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(motasp1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tennhacungcap1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenncctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trangthaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(buttonluu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonluu1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(anhtxt)
                            .addComponent(chonanhbutton)
                            .addComponent(hinhanh, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anhlabble, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chonanhbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonanhbuttonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser(); //sử dụng jfileChooser để cho phép người dùng chọn ảnh
        fileChooser.setDialogTitle("Chọn ảnh");
        fileChooser.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg", "gif"));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            anhtxt.setText(path);

            //hiển thị hình ảnh trong jlabel
//            ImageIcon iconn = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(anhlabble.getWidth(), anhlabble.getHeight(), Image.SCALE_SMOOTH));
//            anhlabble.setIcon(iconn);
            ImageIcon icon = new ImageIcon(path);
            Image img = icon.getImage();
            Image resizedImage = img.getScaledInstance(anhlabble.getWidth(), anhlabble.getHeight(), Image.SCALE_SMOOTH);
            anhlabble.setIcon(new ImageIcon(resizedImage)); // Đặt ảnh đã resize lên JLabel
        }
    }//GEN-LAST:event_chonanhbuttonActionPerformed

    public void showImage(String imagePath) {
        if (imagePath != null && !imagePath.isEmpty()) {
            ImageIcon icon = new ImageIcon(imagePath);
            Image img = icon.getImage();
            Image resizedImage = img.getScaledInstance(anhlabble.getWidth(), anhlabble.getHeight(), Image.SCALE_SMOOTH);
            anhlabble.setIcon(new ImageIcon(resizedImage));
        } else {
            anhlabble.setIcon(null); // Xóa icon nếu không có ảnh
        }
    }

    public void setSanPhamInfo(String masp, String maloai, String tensp, String gia, String mota, String trangthai, String imagePath) {
    // Set các thông tin sản phẩm vào form
    masptxt.setText(masp);
    maloaicombobox.setSelectedItem(maloai);;
    tensptxt.setText(tensp);
    giasptxt.setText(gia);
    motatxt.setText(mota);
    jComboBox1.setSelectedItem(trangthai); // combo box trạng thái
    
    
}


    private void buttonluu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonluu1ActionPerformed
      //   TODO add your handling code here:
        this.dispose();

        //mo lai form san pham
        sanpham sp = new sanpham();
        sp.setVisible(true);
    }//GEN-LAST:event_buttonluu1ActionPerformed

    private void masptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masptxtActionPerformed

    private void buttonluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonluuActionPerformed
        // TODO add your handling code here:
        //phuong thuc nhan du lieu tu sanpham

        //lấy thông tin các trường nhập liệu
        String masp = masptxt.getText().trim();
        String tensp = tensptxt.getText().trim();
        String gia = giasptxt.getText().trim();
        String mota = motatxt.getText().trim();

        //lay gia tri duoc chon trong JCOmbobox
        String ml = (String) maloaicombobox.getSelectedItem();

        String tthai = jComboBox1.getSelectedItem().toString();

        //lấy đường dẫn link hình ảnh từ textfile
        //   String ha = anhtxt.getText().trim();
        //kiem tra du lieu cu the
//       if (masp.isEmpty() || tensp.isEmpty() || gia.isEmpty() || mota.isEmpty() || ha.isEmpty()) {
//    JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
//    return;
//}
// Kiểm tra xem file đã được chọn chưa
        if (this.selectedFile != null) {
            // Nếu file đã được chọn, thực hiện tiếp hành động với file
            String tenAnh = this.selectedFile.getName();
            // Thực hiện các thao tác lưu file
        } else {
            // Nếu không có file nào được chọn, hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một file hình ảnh!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        // Đường dẫn thư mục lưu ảnh trong thư mục của dự án (ví dụ: thư mục "images")
        File destinationDir = new File("images");
        if (!destinationDir.exists()) {
            destinationDir.mkdir(); // Tạo thư mục nếu chưa tồn tại
        }

        // Đặt tên file đích là mã sản phẩm hoặc một tên riêng biệt
        String newFileName = masp + "_" + selectedFile.getName();
        File destinationFile = new File(destinationDir, newFileName);

        try {
            // Sao chép file ảnh vào thư mục "images"
            Files.copy(selectedFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException ex) {
            Logger.getLogger(themsanpham.class.getName()).log(Level.SEVERE, null, ex);
        }
        String relativePath = "images/" + newFileName; // Đường dẫn tương đối của ảnh

        try {
            Connection con1 = ConnectDB.KetnoiDB();
            String check = "select maloai from loaisanpham";
            Statement tt = con1.createStatement();
            ResultSet rs = tt.executeQuery(check);

            Connection con = ConnectDB.KetnoiDB();
            String sql = "INSERT into sanpham Values('" + masp + "',N'" + tensp + "',N'" + ml + "','" + gia + "',N'" + mota + "','" + relativePath + "','" + tthai + "')";

            Statement st = con.createStatement();
            st.executeUpdate(sql);
            con.close();
            JOptionPane.showMessageDialog(this, "Thêm mới thành công !");
            if (parentForm != null) {
                parentForm.load_themsanpham();
                showImage(relativePath); // Hiển thị hình ảnh vừa thêm
            } else {
                JOptionPane.showMessageDialog(this, "Parent form không tồn tại.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

//        //truyền dữ liệu sản phẩm mới về form sản phẩm
//        if (this.getParent() instanceof sanpham) {
//            sanpham parentform = (sanpham) this.getParent();
//            parentform.addSanPham(masp, ml, tensp, gia, mota, tthai, ha);
//        } else {
//            JOptionPane.showMessageDialog(this, "Parent form is not of type sanpham.");
//        }
        //dong form them san pham sau khi luu thanh cong
        this.dispose();
        sanpham sp = new sanpham();
        sp.setVisible(true);
    }//GEN-LAST:event_buttonluuActionPerformed

    private void motatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motatxtActionPerformed

    public void loadCombobox() {

        try {
            Connection con = ConnectDB.KetnoiDB();
            String sqlloai = "SELECT maloai FROM loaisanpham";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sqlloai);
            while (rs.next()) {
                String ml = rs.getString("maloai");
                maloaicombobox.addItem(ml); //them truc tiep ma loai vao combobox
            }
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                themsanpham dialog = new themsanpham(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhlabble;
    private javax.swing.JTextField anhtxt;
    private javax.swing.JButton buttonluu;
    private javax.swing.JButton buttonluu1;
    private javax.swing.JButton chonanhbutton;
    private javax.swing.JLabel giabansanpham1;
    private javax.swing.JTextField giasptxt;
    private javax.swing.JLabel hinhanh;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel maloai;
    private javax.swing.JComboBox<String> maloaicombobox;
    private javax.swing.JLabel masp;
    private javax.swing.JTextField masptxt;
    private javax.swing.JLabel motasp1;
    private javax.swing.JTextField motatxt;
    private javax.swing.JTextField tenncctxt;
    private javax.swing.JLabel tennhacungcap1;
    private javax.swing.JLabel tensp1;
    private javax.swing.JTextField tensptxt;
    private javax.swing.JLabel trangthaisp;
    // End of variables declaration//GEN-END:variables
}
