/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cafe.quanlisp;

import cafe.quanlikh.ConnectDB;
import static com.lowagie.text.pdf.PdfName.USER;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import static org.apache.commons.compress.harmony.pack200.PackingOptions.PASS;

/**
 *
 * @author Admin
 */
public class themsanpham extends javax.swing.JDialog {

    /**
     * Creates new form themsanpham
     */
    public themsanpham(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadCombobox();
    }
    private formsanpham parentForm;

    private File selectedFile;

    public themsanpham(formsanpham parentForm) {
        this.parentForm = parentForm; // Lưu tham chiếu vào biến
        initComponents();
        this.setLocationRelativeTo(null);
        loadCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        masp = new javax.swing.JLabel();
        tensp1 = new javax.swing.JLabel();
        giabansanpham1 = new javax.swing.JLabel();
        motasp1 = new javax.swing.JLabel();
        trangthaisp = new javax.swing.JLabel();
        tennhacungcap1 = new javax.swing.JLabel();
        hinhanh = new javax.swing.JLabel();
        tenncctxt = new javax.swing.JTextField();
        motatxt = new javax.swing.JTextField();
        anhtxt = new javax.swing.JTextField();
        giasptxt = new javax.swing.JTextField();
        tensptxt = new javax.swing.JTextField();
        buttonluu = new javax.swing.JButton();
        maloai = new javax.swing.JLabel();
        masptxt = new javax.swing.JTextField();
        buttonluu1 = new javax.swing.JButton();
        chonanhbutton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        anhlabble = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        soluong = new javax.swing.JLabel();
        soluongtxt = new javax.swing.JTextField();
        maloai1 = new javax.swing.JLabel();
        maloaicombobox1 = new javax.swing.JComboBox<>();
        mancc = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nhập thông tin sản phẩm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        masp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        masp.setText("Mã sản phẩm");

        tensp1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tensp1.setText("Tên sản phẩm");

        giabansanpham1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        giabansanpham1.setText("Giá bán sản phẩm");

        motasp1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        motasp1.setText("Mô tả sản phẩm");

        trangthaisp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        trangthaisp.setText("Trạng thái sản phẩm");

        tennhacungcap1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tennhacungcap1.setText("Tên nhà cung cấp");

        hinhanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hinhanh.setText("Hình ảnh sản phẩm");

        tenncctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenncctxtActionPerformed(evt);
            }
        });

        motatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motatxtActionPerformed(evt);
            }
        });

        anhtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anhtxtActionPerformed(evt);
            }
        });

        buttonluu.setBackground(new java.awt.Color(177, 151, 125));
        buttonluu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonluu.setForeground(new java.awt.Color(255, 255, 255));
        buttonluu.setText("Thêm");
        buttonluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonluuActionPerformed(evt);
            }
        });

        maloai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maloai.setText("Mã loại");

        masptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masptxtActionPerformed(evt);
            }
        });

        buttonluu1.setBackground(new java.awt.Color(177, 151, 125));
        buttonluu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonluu1.setForeground(new java.awt.Color(255, 255, 255));
        buttonluu1.setText("Hủy");
        buttonluu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonluu1ActionPerformed(evt);
            }
        });

        chonanhbutton.setText("Chọn ảnh");
        chonanhbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonanhbuttonActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn hàng", "Hết hàng", "Ngừng bán" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Thêm sản phẩm");

        soluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soluong.setText("Số lượng");

        maloai1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maloai1.setText("Mã nhà cung cấp");

        maloaicombobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maloaicombobox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(hinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chonanhbutton)
                            .addGap(12, 12, 12))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(masp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tensp1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(giabansanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(motasp1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(trangthaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tennhacungcap1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(maloai1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(anhlabble, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(buttonluu)
                        .addGap(70, 70, 70)
                        .addComponent(buttonluu1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(motatxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(giasptxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tensptxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(masptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maloai, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maloaicombobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(tenncctxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(soluongtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(anhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(masptxt)
                            .addComponent(maloai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maloaicombobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(masp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tensp1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(tensptxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(giabansanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giasptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(soluongtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motasp1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maloai1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenncctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tennhacungcap1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trangthaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chonanhbutton)
                    .addComponent(anhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonluu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonluu1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(anhlabble, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chonanhbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonanhbuttonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn ảnh sản phẩm");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

// Khai báo biến để lưu đường dẫn ảnh
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile(); // Lưu file đã chọn vào biến selectedFile
            String filePath = selectedFile.getAbsolutePath(); // Lấy đường dẫn file ảnh
            System.out.println("File đã chọn: " + filePath);

            // Hiển thị ảnh lên JLabel
            ImageIcon icon = new ImageIcon(filePath);
            Image img = icon.getImage();
            Image resizedImage = img.getScaledInstance(anhlabble.getWidth(), anhlabble.getHeight(), Image.SCALE_SMOOTH);
            anhlabble.setIcon(new ImageIcon(resizedImage)); // Đặt ảnh đã resize lên JLabel
        }
        String masp = masptxt.getText().trim();
        String newFileName = masp + "_" + selectedFile.getName();
        anhtxt.setText(newFileName);

    }//GEN-LAST:event_chonanhbuttonActionPerformed

    public void showImage(String imagePath) {
        if (imagePath != null && !imagePath.isEmpty()) {
            ImageIcon icon = new ImageIcon(imagePath);
            Image img = icon.getImage();
            Image resizedImage = img.getScaledInstance(anhlabble.getWidth(), anhlabble.getHeight(), Image.SCALE_SMOOTH);
            anhlabble.setIcon(new ImageIcon(resizedImage));
        } else {
            anhlabble.setIcon(null); // Xóa icon nếu không có ảnh
        }
    }

    public void setSanPhamInfo(String masp, String maloai, String tensp, String gia, String mota, String trangthai, String imagePath, String macongty, String soluong) {
        // Set các thông tin sản phẩm vào form
        masptxt.setText(masp);
        maloaicombobox1.setSelectedItem(maloai);
        tensptxt.setText(tensp);
        giasptxt.setText(gia);
        motatxt.setText(mota);
        jComboBox1.setSelectedItem(trangthai); // combo box trạng thái
        mancc.setText(macongty);
        soluongtxt.setText(soluong);
        

    }


    private void buttonluu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonluu1ActionPerformed
        //   TODO add your handling code here:
        this.dispose();

        //mo lai form san pham
        formsanpham sp = new formsanpham();
        sp.setVisible(true);
    }//GEN-LAST:event_buttonluu1ActionPerformed

    private void masptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masptxtActionPerformed

    private void buttonluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonluuActionPerformed
        // TODO add your handling code here:
        //phuong thuc nhan du lieu tu sanpham

        //lấy thông tin các trường nhập liệu
        String masp = masptxt.getText().trim();
        String tensp = tensptxt.getText().trim();
        String gia = giasptxt.getText().trim();
        String mota = motatxt.getText().trim();

        //lay gia tri duoc chon trong JCOmbobox
        String ml = (String) maloaicombobox1.getSelectedItem();

        String tthai = (String)jComboBox1.getSelectedItem().toString();
         String mncc = mancc.getText().trim();
        String soluong = soluongtxt.getText().trim();
       

        if (selectedFile == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn ảnh trước khi lưu!");
            return;
        }
        // Đường dẫn thư mục lưu ảnh trong thư mục của dự án (ví dụ: thư mục "images")
        File destinationDir = new File("images");
        if (!destinationDir.exists()) {
            destinationDir.mkdir(); // Tạo thư mục nếu chưa tồn tại
        }

        // Đặt tên file đích là mã sản phẩm hoặc một tên riêng biệt
        String newFileName = masp + "_" + selectedFile.getName();
        File destinationFile = new File(destinationDir, newFileName);

        try {
            // Sao chép file ảnh vào thư mục "images"
            Files.copy(selectedFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException ex) {
            Logger.getLogger(themsanpham.class.getName()).log(Level.SEVERE, null, ex);
        }
        String relativePath = "images/" + newFileName; // Đường dẫn tương đối của ảnh

        try {
            Connection con1 = ConnectDB.KetnoiDB();
            String check = "select maloai from loaisanpham";
            Statement tt = con1.createStatement();
            ResultSet rs = tt.executeQuery(check);

            Connection con = ConnectDB.KetnoiDB();
            String sql = "INSERT into sanpham Values('" + masp + "',N'" + tensp + "',N'" + ml + "','" + gia + "',N'" + mota + "','" + relativePath + "','" + tthai + "','" + mncc + "','" + soluong + "')";

            Statement st = con.createStatement();
            st.executeUpdate(sql);
            con.close();
            JOptionPane.showMessageDialog(this, "Thêm mới thành công !");
            if (parentForm != null) {
                parentForm.load_themsanpham();
                showImage(relativePath); // Hiển thị hình ảnh vừa thêm
            }
//            } else {
//                JOptionPane.showMessageDialog(this, "Parent form không tồn tại.");
//            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        //truyền dữ liệu sản phẩm mới về form sản phẩm
//        if (this.getParent() instanceof formsanpham) {
//            formsanpham parentform = (formsanpham) this.getParent();
//            parentform.addSanPham(masp, ml, tensp, gia, mota, tthai, ha);
//        } else {
//            JOptionPane.showMessageDialog(this, "Parent form is not of type sanpham.");
//        }
        //dong form them san pham sau khi luu thanh cong
        this.dispose();
        formsanpham sp = new formsanpham();
        sp.setVisible(true);
    }//GEN-LAST:event_buttonluuActionPerformed

    private void motatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motatxtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_motatxtActionPerformed

    private void anhtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anhtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anhtxtActionPerformed

    private void tenncctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenncctxtActionPerformed
        // TODO add your handling code here:
//        String tenCongTy = tenncctxt.getText().trim();
//        if (!tenCongTy.isEmpty()) {
//            updateMaCongTy(tenCongTy);
//        }
    }//GEN-LAST:event_tenncctxtActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    private void maloaicombobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maloaicombobox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maloaicombobox1ActionPerformed

    // Cập nhật tên công ty dựa trên mã công ty
    private void updateTenCongTy(String maCongTy) {
        try {
            // Kết nối tới cơ sở dữ liệu
            Connection conn = ConnectDB.KetnoiDB();
            String query = "SELECT tencongty FROM nhacungcap WHERE macongty = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, maCongTy);

            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                tenncctxt.setText(rs.getString("tenCongTy"));
            } else {
                tenncctxt.setText("Không tìm thấy tên công ty");
            }
            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public void YourFormConstructor() {
    initComponents();
    
    // Lắng nghe sự kiện cho trường nhập liệu
    tenncctxt.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String tenCongTy = tenncctxt.getText().trim();
            if (!tenCongTy.isEmpty()) {
                updateMaCongTy(tenCongTy);
            }
        }
    });

    mancc.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String maCongTy = mancc.getText().trim();
            if (!maCongTy.isEmpty()) {
                updateTenCongTy(maCongTy);
            }
        }
    });
    }
    // Cập nhật mã công ty dựa trên tên công ty
    private void updateMaCongTy(String tenCongTy) {
        try {
            // Kết nối tới cơ sở dữ liệu
            Connection conn = ConnectDB.KetnoiDB();
            String query = "SELECT macongty FROM nhacungcap WHERE tencongty = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, tenCongTy);

            ResultSet rs = stmt.executeQuery();
              if (rs.next()) {
                mancc.setText(rs.getString("maCongTy"));
            } else {
                mancc.setText("Không tìm thấy mã công ty");
            }
            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public void loadCombobox() {

        try {
            Connection con = ConnectDB.KetnoiDB();
            String sqlloai = "SELECT maloai FROM loaisanpham";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sqlloai);
            while (rs.next()) {
                String ml = rs.getString("maloai");
                maloaicombobox1.addItem(ml); //them truc tiep ma loai vao combobox
            }
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                themsanpham dialog = new themsanpham(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhlabble;
    private javax.swing.JTextField anhtxt;
    private javax.swing.JButton buttonluu;
    private javax.swing.JButton buttonluu1;
    private javax.swing.JButton chonanhbutton;
    private javax.swing.JLabel giabansanpham1;
    private javax.swing.JTextField giasptxt;
    private javax.swing.JLabel hinhanh;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel maloai;
    private javax.swing.JLabel maloai1;
    private javax.swing.JComboBox<String> maloaicombobox1;
    private javax.swing.JTextField mancc;
    private javax.swing.JLabel masp;
    private javax.swing.JTextField masptxt;
    private javax.swing.JLabel motasp1;
    private javax.swing.JTextField motatxt;
    private javax.swing.JLabel soluong;
    private javax.swing.JTextField soluongtxt;
    private javax.swing.JTextField tenncctxt;
    private javax.swing.JLabel tennhacungcap1;
    private javax.swing.JLabel tensp1;
    private javax.swing.JTextField tensptxt;
    private javax.swing.JLabel trangthaisp;
    // End of variables declaration//GEN-END:variables
}
