/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package cafe.quanlisp;

import cafe.quanlikh.ConnectDB;
import cafe.quanlisp.formsanpham;
import static com.lowagie.text.pdf.PdfName.USER;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import static org.apache.commons.compress.harmony.pack200.PackingOptions.PASS;

/**
 *
 * @author Admin
 */
public class xoathongtin extends javax.swing.JDialog {

    /**
     * Creates new form themsanpham
     */
    public xoathongtin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    private formsanpham parentForm;
    private JLabel lblImage;
    private File selectedFile;
    public xoathongtin(formsanpham parent) {
        this.parentForm = parent; // Lưu tham chiếu vào biến
        initComponents();
        this.setLocationRelativeTo(null);
        lblImage = new JLabel();
        add(lblImage);
        loadCombobox();
    }
    public void loadCombobox() {

        try {
            Connection con = ConnectDB.KetnoiDB();
            String sqlloai = "SELECT maloai FROM loaisanpham";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sqlloai);
            while (rs.next()) {
                String ml = rs.getString("maloai");
                maloaicombobox1.addItem(ml); //them truc tiep ma loai vao combobox
            }
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private JTextField txtMaloai;
    private JTextField txtTensp;
    private JTextField txtMasp;
    private JTextField txtGia;
    private JTextField txtMota;
    private JTextField txtMCT;
    private JTextField txtSoluong;
    private JTextField txtAnh;
    private JTextField txtTrangthai;
         
    
    //phuong thuc de dat gia tri cho ma loai
    public void setMaloai(String maloai){
        txtMaloai.setText(maloai);
    }
    public void setTensp(String tensp){
        txtTensp.setText(tensp);
    }
    public void setMasp(String masp){
        txtMasp.setText(masp);
    }
    public void setGia(String gia){
        txtGia.setText(gia);
    }
    public void setMota(String mota){
        txtMota.setText(mota);
    }
    public void setMCT(String mact){
        txtMCT.setText(mact);
    }
    public void setSoluong(String soluong){
        txtSoluong.setText(soluong);
    }
    public void setanh(String anh){
        txtAnh.setText(anh);
    }
    public void setTrangthai(String trangthai){
        txtTrangthai.setText(trangthai);
    }
    
    //phuong thức để nhận dữ liệu sản phẩm từ form sản phẩm
    public void setProductData(String masp, String maloai, String tensp, String gia, String mota, String trangthai, String hinhanh, String macongty, String soluong) {
        masptxt.setText(masp);
        maloaicombobox1.setSelectedItem(maloai);
        tensptxt.setText(tensp);
        giasptxt.setText(gia);
        motatxt.setText(mota);
        jComboBox1.setSelectedItem(trangthai);
        anhtxt.setText(hinhanh);//gán đường dẫn hình ảnh vào ô text
        anhlabble.setIcon(new ImageIcon(hinhanh)); //hiển thị hình ảnh
        mancc.setText(macongty);
        soluongtxt.setText(soluong);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        masp = new javax.swing.JLabel();
        tensp1 = new javax.swing.JLabel();
        giabansanpham1 = new javax.swing.JLabel();
        motasp1 = new javax.swing.JLabel();
        trangthaisp = new javax.swing.JLabel();
        tennhacungcap1 = new javax.swing.JLabel();
        hinhanh = new javax.swing.JLabel();
        tenncctxt = new javax.swing.JTextField();
        motatxt = new javax.swing.JTextField();
        anhtxt = new javax.swing.JTextField();
        giasptxt = new javax.swing.JTextField();
        tensptxt = new javax.swing.JTextField();
        buttonxoa = new javax.swing.JButton();
        maloai = new javax.swing.JLabel();
        masptxt = new javax.swing.JTextField();
        buttonhuy = new javax.swing.JButton();
        chonanhbutton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        anhlabble = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        soluong = new javax.swing.JLabel();
        soluongtxt = new javax.swing.JTextField();
        maloai1 = new javax.swing.JLabel();
        maloaicombobox1 = new javax.swing.JComboBox<>();
        mancc = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText(" Thông tin xóa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        masp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        masp.setText("Mã sản phẩm");

        tensp1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tensp1.setText("Tên sản phẩm");

        giabansanpham1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        giabansanpham1.setText("Giá bán sản phẩm");

        motasp1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        motasp1.setText("Mô tả sản phẩm");

        trangthaisp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        trangthaisp.setText("Trạng thái sản phẩm");

        tennhacungcap1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tennhacungcap1.setText("Tên nhà cung cấp");

        hinhanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hinhanh.setText("Hình ảnh sản phẩm");

        tenncctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenncctxtActionPerformed(evt);
            }
        });

        motatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motatxtActionPerformed(evt);
            }
        });

        anhtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anhtxtActionPerformed(evt);
            }
        });

        buttonxoa.setBackground(new java.awt.Color(177, 151, 125));
        buttonxoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonxoa.setForeground(new java.awt.Color(255, 255, 255));
        buttonxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash.png"))); // NOI18N
        buttonxoa.setText(" Xóa");
        buttonxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonxoaActionPerformed(evt);
            }
        });

        maloai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maloai.setText("Mã loại");

        masptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masptxtActionPerformed(evt);
            }
        });

        buttonhuy.setBackground(new java.awt.Color(153, 204, 255));
        buttonhuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonhuy.setForeground(new java.awt.Color(255, 255, 255));
        buttonhuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel.png"))); // NOI18N
        buttonhuy.setText(" Hủy");
        buttonhuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonhuyActionPerformed(evt);
            }
        });

        chonanhbutton.setText("Chọn ảnh");
        chonanhbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonanhbuttonActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn hàng", "Hết hàng", "Ngừng bán" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jLabel3.setText("Xóa thông tin sản phẩm");

        soluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soluong.setText("Số lượng");

        maloai1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maloai1.setText("Mã nhà cung cấp");

        maloaicombobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maloaicombobox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(hinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chonanhbutton)
                            .addGap(12, 12, 12))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(masp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tensp1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(giabansanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(motasp1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(trangthaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tennhacungcap1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(maloai1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(anhlabble, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(buttonxoa)
                        .addGap(70, 70, 70)
                        .addComponent(buttonhuy))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(motatxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(giasptxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tensptxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(masptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maloai, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maloaicombobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(tenncctxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(soluongtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(anhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maloaicombobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(masp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(maloai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(masptxt, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tensp1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(tensptxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(giabansanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giasptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(soluongtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motasp1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maloai1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mancc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenncctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tennhacungcap1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trangthaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chonanhbutton)
                    .addComponent(anhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonhuy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(anhlabble, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chonanhbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonanhbuttonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn ảnh sản phẩm");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

// Khai báo biến để lưu đường dẫn ảnh
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile(); // Lưu file đã chọn vào biến selectedFile
            String filePath = selectedFile.getAbsolutePath(); // Lấy đường dẫn file ảnh
            System.out.println("File đã chọn: " + filePath);

            // Hiển thị ảnh lên JLabel
            ImageIcon icon = new ImageIcon(filePath);
            Image img = icon.getImage();
            Image resizedImage = img.getScaledInstance(anhlabble.getWidth(), anhlabble.getHeight(), Image.SCALE_SMOOTH);
            anhlabble.setIcon(new ImageIcon(resizedImage)); // Đặt ảnh đã resize lên JLabel
        }
        String masp = masptxt.getText().trim();
        String newFileName = masp + "_" + selectedFile.getName();
        anhtxt.setText(newFileName);
    }//GEN-LAST:event_chonanhbuttonActionPerformed

public void lockMaSP() {
        masptxt.setEditable(false); // Khóa ô mã sản phẩm để không cho chỉnh sửa
    }

public void showImage(String imagePath) {
//    if (imagePath != null && !imagePath.isEmpty()) {
//        lblImage.setIcon(new ImageIcon(imagePath)); // Hiển thị ảnh trên JLabel
//    }
        if (imagePath != null && !imagePath.isEmpty()) {
            ImageIcon icon = new ImageIcon(imagePath);
            Image img = icon.getImage();
            Image resizedImage = img.getScaledInstance(anhlabble.getWidth(), anhlabble.getHeight(), Image.SCALE_SMOOTH);
            anhlabble.setIcon(new ImageIcon(resizedImage));
        } else {
            anhlabble.setIcon(null); // Nếu không có ảnh, xoá icon
        }
    }
public void opensuathongtin(String ma, String tensp, String maloai, String gia, String mota, String ha, String tt, String macongty, String soluong){
    xoathongtin formsua = new xoathongtin(ma, tensp, maloai, gia, mota, ha, tt, macongty, soluong);
    formsua.setVisible(true);
    
}

public xoathongtin(String ma , String tensp, String maloai, String gia, String mota, String ha, String tt, String macongty, String soluong){
        masptxt.setText(ma);
        maloaicombobox1.setSelectedItem(maloai);
        tensptxt.setText(tensp);
        giasptxt.setText(gia);
        motatxt.setText(mota);
        jComboBox1.setSelectedItem(tt);
        anhtxt.setText(ha);//gán đường dẫn hình ảnh vào ô text
        anhlabble.setIcon(new ImageIcon(ha)); //hiển thị hình ảnh
        mancc.setText(macongty);
        soluongtxt.setText(soluong);
}

 public void setSanPhamInfo(String masp, String maloai, String tensp, String gia, String mota, String trangthai, String hinhanh,String macongty, String soluong) {
        masptxt.setText(masp);
        maloaicombobox1.setSelectedItem(maloai);
        tensptxt.setText(tensp);
        giasptxt.setText(gia);
        motatxt.setText(mota);
        jComboBox1.setSelectedItem(trangthai);
        anhtxt.setText(hinhanh);
        // Lưu đường dẫn ảnh vào JTextField hoặc JLabel
        showImage(hinhanh);
        mancc.setText(macongty);
        soluongtxt.setText(soluong);
        
        
    }
 
    private void buttonhuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonhuyActionPerformed
        //   TODO add your handling code here:
        this.dispose();

        //mo lai form san pham
        formsanpham sp = new formsanpham();
        sp.setVisible(true);
    }//GEN-LAST:event_buttonhuyActionPerformed

    private void masptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masptxtActionPerformed

    private void buttonxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonxoaActionPerformed
        // TODO add your handling code here:
       try {
            String sp = masptxt.getText().trim();
            Connection con = ConnectDB.KetnoiDB();
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirm == 0) {
                String sql = "Delete from sanpham where masp='" + sp + "' ";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công!");
                con.close();
                dispose();
                if (parentForm != null) {
                    parentForm.load_themsanpham();// Gọi hàm load_km() từ form gốc
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa không thành công");
            e.printStackTrace();
        }
       
       this.dispose();
       formsanpham form222 = new formsanpham();
       form222.setVisible(true);
        
    }//GEN-LAST:event_buttonxoaActionPerformed

    public xoathongtin(JFrame parent, String masp, String maloai, String tensp, String mota, String gia, String hinhanh, String trangthai, String macongty, String soluong){
        super(parent, true); // Gọi constructor của JDialog với form cha
        initComponents();
        
        //hiển thị dữ liệu sản phẩm lên form
        masptxt.setText(masp);
        maloaicombobox1.setSelectedItem(maloai);
        tensptxt.setText(tensp);
        giasptxt.setText(gia);    
        motatxt.setText(mota);
        jComboBox1.setSelectedItem(trangthai);       
        anhtxt.setText(hinhanh);
        showImage(hinhanh);
        mancc.setText(macongty);
        soluongtxt.setText(soluong);
        
        masptxt.setEditable(false); // khóa mã sản phẩm không cho chỉnh sửa
    }
   





   
    private void motatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motatxtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_motatxtActionPerformed

    private void anhtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anhtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anhtxtActionPerformed

    private void tenncctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenncctxtActionPerformed
       
    }//GEN-LAST:event_tenncctxtActionPerformed

    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    private void maloaicombobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maloaicombobox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maloaicombobox1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xoathongtin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xoathongtin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xoathongtin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xoathongtin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                xoathongtin dialog = new xoathongtin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhlabble;
    private javax.swing.JTextField anhtxt;
    private javax.swing.JButton buttonhuy;
    private javax.swing.JButton buttonxoa;
    private javax.swing.JButton chonanhbutton;
    private javax.swing.JLabel giabansanpham1;
    private javax.swing.JTextField giasptxt;
    private javax.swing.JLabel hinhanh;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel maloai;
    private javax.swing.JLabel maloai1;
    private javax.swing.JComboBox<String> maloaicombobox1;
    private javax.swing.JTextField mancc;
    private javax.swing.JLabel masp;
    private javax.swing.JTextField masptxt;
    private javax.swing.JLabel motasp1;
    private javax.swing.JTextField motatxt;
    private javax.swing.JLabel soluong;
    private javax.swing.JTextField soluongtxt;
    private javax.swing.JTextField tenncctxt;
    private javax.swing.JLabel tennhacungcap1;
    private javax.swing.JLabel tensp1;
    private javax.swing.JTextField tensptxt;
    private javax.swing.JLabel trangthaisp;
    // End of variables declaration//GEN-END:variables
}
