/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe;

import cafe.User;
import cafe.baocaoquanli.bao;
import cafe.baocaoquanli.km;
import cafe.nhacungcap.nhacungcap;
import cafe.quanlihoadon.Dashboard;
import cafe.quanlihoadon.ThemHoaDon;
import cafe.quanlikh.ConnectDB;
import cafe.quanlikh.main;
import cafe.quanlikh.suakh;
import cafe.quanlinhanvien.nv;
import cafe.quanlisp.sp;
import cafe.thongke.thongke;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon logo = new ImageIcon(getClass().getResource("/icon/coffee.png"));
        setIconImage(logo.getImage());
        setTitle("Đăng nhập");
        txtTaiKhoan.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_TAB) {
                    txtMatKhau.requestFocus();
                    evt.consume(); // Ngăn chặn sự kiện Tab mặc định
                }
            }
        });
        // Thêm sự kiện Enter cho txttaikhoan
        txtTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDangNhapActionPerformed(evt);
            }
        });

        // Thêm sự kiện Enter cho txtmatkhau
        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDangNhapActionPerformed(evt);
            }
        });
    }

    private void setFocusTraversal() {
        txtTaiKhoan.setNextFocusableComponent(txtMatKhau);
        txtMatKhau.setNextFocusableComponent(txtTaiKhoan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtShow = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonDangNhap = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 330, 30));

        txtShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/unseen.png"))); // NOI18N
        txtShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtShowMouseClicked(evt);
            }
        });
        jPanel1.add(txtShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 360, 30, 30));
        jPanel1.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 330, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/padlock.png"))); // NOI18N
        jLabel1.setText("Mật khẩu:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/id-card.png"))); // NOI18N
        jLabel2.setText("Tên đăng nhập:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, -1, -1));

        buttonDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonDangNhap.setForeground(new java.awt.Color(0, 102, 51));
        buttonDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/enter.png"))); // NOI18N
        buttonDangNhap.setText("   Đăng nhập");
        buttonDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(buttonDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Đăng nhập");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDangNhapActionPerformed

        String tkk = txtTaiKhoan.getText().trim();
        char[] password = txtMatKhau.getPassword();
        String mkk = new String(password);
        try {
            Connection con = ConnectDB.KetnoiDB();

            // Truy vấn để lấy thông tin nhân viên theo tài khoản và mật khẩu
            String sql = "select manv, tennhanvien, chucvu, sodienthoai, taikhoan, matkhau from nhanvien where taikhoan=? and matkhau=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, tkk);
            pst.setString(2, mkk);
            ResultSet rs = pst.executeQuery();

            // Kiểm tra xem có kết quả trả về không
            if (rs.next()) {
                // Lấy thông tin nhân viên từ kết quả truy vấn
                String manv = rs.getString("manv");
                String ten = rs.getString("tennhanvien");
                String vaitro = rs.getString("chucvu");
                String sodienthoai = rs.getString("sodienthoai");
                String taikhoan = rs.getString("taikhoan");
                String matkhau = rs.getString("matkhau");

                // Tạo một đối tượng User và lưu thông tin vào đó
                User user = new User(manv, ten, vaitro, sodienthoai, taikhoan, matkhau);

                // Kiểm tra vai trò của người dùng
                if (vaitro.equals("Admin") || vaitro.equals("Quản lý")) {
                    nv tkh = new nv();
                    tkh.setuser(user); // Sử dụng thông tin từ class User
                    tkh.show();
                    dispose(); // Đóng màn hình đăng nhập
                } else {
                    km d = new km();
                    nhacungcap n = new nhacungcap();
                    Dashboard a = new Dashboard();
                    main m = new main();
                    nv v = new nv();
                    sp p = new sp();
                    thongke k = new thongke();
                    ThemHoaDon b = new ThemHoaDon();
                    d.setuser(user);
                    d.show();
                    //b.setMaNhanVien(user);
                    //a.setuser(user);
                    //d.user(user.getTaikhoan(), user.getChucvu()); // Sử dụng thông tin từ class User
                    dispose(); // Đóng màn hình đăng nhập
                }
            } else {
                JOptionPane.showMessageDialog(this, "Thông tin đăng nhập không đúng");
            }

            // Đóng kết nối sau khi sử dụng
            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

//        String tkk = tk.getText().trim();
//        String mkk = mk.getText().trim();
//        try {
//            Connection con = ConnectDB.KetnoiDB();
//            String sql = "select chucvu,tennhanvien from nhanvien where taikhoan='" + tkk + "' and matkhau='" + mkk + "'";
//            Statement st = con.createStatement();
//            ResultSet rs = st.executeQuery(sql);
//            if (rs.next()) {
//                String vaitro = rs.getString("chucvu");
//                String ten = rs.getString("tennhanvien");
//                if (vaitro.equals("Admin") || vaitro.equals("Quản lý")) {
//                    nv tkh = new nv();
//                    tkh.user(tkk, vaitro);
//                    tkh.show();
//                    dispose();
//                } else {
////                    bao tkh = new bao();
////                    tkh.show();
////                    dispose();
//                    Dashboard d = new Dashboard();
//                    d.show();
//                    d.user(tkk, vaitro);
//                    dispose();
//
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Thông tin đăng nhập không đúng");
//            }
//            con.close();
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_buttonDangNhapActionPerformed
    private boolean isPasswordVisible = false;
    private void txtShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtShowMouseClicked
        if (isPasswordVisible) {
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/unseen.png"));
            txtShow.setIcon(icon);
            // Nếu mật khẩu đang được hiển thị, chuyển về dạng ẩn
            txtMatKhau.setEchoChar('*'); // Đặt lại ký tự hiển thị thành '*'
            txtShow.setText("Hiện mật khẩu"); // Thay đổi tiêu đề nút
        } else {
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/eye.png"));
            txtShow.setIcon(icon);
            // Nếu mật khẩu đang bị ẩn, hiển thị mật khẩu
            txtMatKhau.setEchoChar((char) 0); // Đặt ký tự hiển thị thành không có ký tự nào
            txtShow.setText("Ẩn mật khẩu"); // Thay đổi tiêu đề nút
        }

        isPasswordVisible = !isPasswordVisible; // Chuyển đổi trạng thái hiển thị

    }//GEN-LAST:event_txtShowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JLabel txtShow;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
